server:
  port: 8080

spring:
  application:
    name: jms-test

# IBM MQ 配置
ibm:
  mq:
    queue-manager: MQJ006D
    channel: DEV.ADMIN.SVRCONN
    conn-name: localhost(3434)
    user: mqm

# 自定義 MQ 配置
mq-config:
  queue-name: DEV.QUEUE.1
