server:
  port: 8090

spring:
  application:
    name: jms-test

# IBM MQ 配置
ibm:
  mq:
    queue-manager: MQJ006D
    channel: DEV.APP.SVRCONN
    conn-name: localhost(3434)
    user: mqm

# MQ 配置
mq-config:
  queue-name: DEV.QUEUE.1
