server:
  port: 8090

spring:
  application:
    name: jms-test
  main:
    allow-circular-references: true

# IBM MQ 配置
ibm:
  mq:
    queue-manager: MQJ006D
    channel: DEV.APP.SVRCONN
    conn-name: localhost(3434)
    user: mqm

# MQ 配置
mq-config:
  queue-name: DEV.QUEUE.1
  message-ttl-seconds: 100
  reconnect-interval-seconds: 30
  max-reconnect-attempts: 5
  reconnect-pause-minutes: 30
